services:
  app:
    container_name: medio_app
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    volumes:
      - ../:/var/www/html
    ports:
    - "80:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=medio
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - PHP_XDEBUG_ENABLED=1
      - PHP_IDE_CONFIG=serverName=docker
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal

  db:
    container_name: medio_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medio
    ports:
      - "3306:3306"
